<?php

namespace App\Controllers\Admin;

use App\Controllers\BaseController;
use TCPDF;
use App\Models\AnggotaModel;
use App\Models\NotaModel;

class Cetakkelas extends BaseController
{
    private $pdf;
    public function __construct()
    {
    //   parent::construct();
      $this->angg = new AnggotaModel();
      $this->nota = new NotaModel();
      $this->pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, array(200,300));
    }

    public function generatePdf($nota = null, $jurs=null, $kls=null)
    {
        // $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, array(200,300));
        $pdf=$this->pdf;
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('kang_didikw|k-dir');
        $pdf->SetTitle('cetaKartu');
        $pdf->SetSubject('cetaKartu');
        $pdf->SetKeywords('SMKNNgadirojo,'.$jurs);
        $pdf->setPrintHeader(false);

        $pdf->SetMargins(4,4,4);
        $pdf->SetAutoPageBreak(1,5);
        $pdf->SetLineWidth(0.1);
        $pdf->AddPage();

        //dfcard
        $boxw=96;
        $boxh=56;
        $bgw=87;
        $bgh=55;
        $ml = 4;
        $mt = 4; //4
        $bg1 = base_url('uploads/'.$nota.'/bg1_'.$nota.'.jpg');
        $bg2 = base_url('uploads/'.$nota.'/bg2_'.$nota.'.jpg');
        $ttd = base_url('uploads/'.$nota.'/stp_'.$nota.'.png');
        $plong='';
        //dfcard
        //pdfStyle
        $qrsty = array(
            'border' => 2,
            'padding' => '2',
            'fgcolor' => array(29,32,136),
            'bgcolor' => array(255,255,255), //array(255,255,255)
            'module_width' => 1, // width of a single module in points
            'module_height' => 1 // height of a single module in points
        );
        $data=$this->angg->cetakKelas($nota, $jurs, $kls);
        
        $nt=$this->nota->getNota1($nota);
        $tmpl=$nt->nt_tmpl;
        $i=-1;
        $row=0;
        $ct=count($data);
        // $pdf->Ln(5);
        // $pdf->Cell(20, 0, 'Title', 1, 1, 'C');
        // $pdf->Rect($ml,$row*$boxh+$mt,$boxw,$boxh,'D');//mal
        foreach($data as $key=>$dt){
            $i++;
            $row=$i%5;
            $foto= base_url('uploads/'.$nota.'/'.$dt->ag_nisn.'.jpg');
            $nisn=$dt->ag_nisn;
            $nama=strtoupper($dt->ag_nama);
            $nis=$dt->ag_induk;
            $prodi=$dt->ag_jurusan;
            $tgll=$dt->ag_tgl=='0000-00-00'?$dt->ag_tgl:date_id(date('Y-m-d', strtotime($dt->ag_tgl)));
            $lahir=$dt->ag_tempat.', '.$tgll;
            $ortu='Ortu '.$dt->ag_bapak;
            $alamat1='RT '.$dt->ag_rt.' RW '.$dt->ag_rw.' '.$dt->ag_dusun.' Desa '.$dt->ag_desa;
            $alamat2='Kec '.$dt->ag_kec.', '.$dt->ag_kab;
            $sekolah=$nt->sch_nama;
            $ks=$nt->nt_ks;
            $nip=$nt->nt_nip;
            $tgl=$nt->nt_tgl;
            $nick=$dt->ag_nick;

            // startL
            $pdf->Rect($ml,$row*$boxh+$mt,$boxw,$boxh,'D');//mal
            $pdf->Image($bg1,$ml+4.5,$row*$boxh+$mt+0.5,$bgw, $bgh); //bg
            // $pdf->Image(base_url('uploads/bg1wm.jpg'),$ml+4.5,$row*$boxh+$mt+0.5,$bgw, $bgh); //bg watermark
            $this->$tmpl($ml,$row,$boxh,$boxw,$bgh,$nisn,$nama,$nis,$prodi,$lahir,$ortu,$alamat1,$alamat2,$sekolah,$ks,$nip,$foto,$ttd,$tgl,$nick,$qrsty,$bg2, $plong); //pilih template
            // $pdf->Rect($ml+5,$row*$boxh+$mt+1,$bgw-1,$bgh-1,'D'); //batas potong kartu
            // endL
            // ==================================================================================
            // startR
            $pdf->Rect($ml+$boxw,$row*$boxh+$mt,$boxw,$boxh,'D');//Mal
            // $pdf->Rect($ml+$boxw+5,$mt+1,$bgw-1,$bgh-1,'D'); //batas potong kartu
            // endR
            if(($row%5==4 AND $key<$ct-1)){
                $pdf->AddPage();
            }
        }
        // dd('CetakPDF'.$nota.'_'.$jurs.'.pdf');
        $this->response->setContentType('application/pdf');
        $pdf->Output('CetaKartu_'.$nota.'_'.$sekolah.'_'.$jurs.$kls.'.pdf', 'I');
    }
    public function allpdf_pecah($nota = null){
        $data=$this->angg->getAnggota($nota);
        foreach($data as $key=>$dt){
            $pdf = new TCPDF();
            // Set informasi dokumen
            $pdf->SetCreator(PDF_CREATOR);
            $pdf->SetAuthor('Nama Penulis');
            $pdf->SetTitle($dt->ag_nisn);
            $pdf->SetSubject('Contoh PDF');
            $pdf->SetKeywords('TCPDF, PDF, example, test, guide');
        
            // Set default header data
            $pdf->SetHeaderData('', 0, $dt->ag_nisn, 'Generated by TCPDF');
        
            // Set header dan footer
            $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
            $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
            $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
            $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
            $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
            $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
        
            // Tambah halaman
            $pdf->AddPage();
        
            // Isi konten PDF
            $pdf->SetFont('helvetica', '', 12);
            $pdf->Write(0, $dt->ag_nisn, '', 0, 'L', true, 0, false, false, 0);
        
            // Simpan PDF ke file terpisah
            $filename = $dt->ag_nisn . '.pdf';
            $pdf->Output($filename, 'I'); // 'F' untuk simpan ke file
        }
    }
    public function pribadiPdf($nota = null, $nisn=null, $ctk=null)
    {
        // $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, array(200,300));
        $pdf=$this->pdf;
    

        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('kang_didikw|k-dir');
        $pdf->SetTitle('cetaKartu');
        $pdf->SetSubject('cetaKartu');
        $pdf->SetKeywords('SMKNNgadirojo');
        $pdf->setPrintHeader(false);
        $pdf->SetMargins(4,4,4);
        $pdf->SetAutoPageBreak(1,5);
        $pdf->AddPage();

        // $ctk=2; #1=cetak, 2=filepdf
        $boxw=96;
        $boxh=56;
        $bgw=87;
        $bgh=55;
        $ml = 4;
        $mt = 4;
        $bg1 = base_url('uploads/'.$nota.'/bg1_'.$nota.'.jpg');
        $bg2 = base_url('uploads/'.$nota.'/bg2_'.$nota.'.jpg');
        $plong= base_url('uploads/id_plong.png');
        $ttd = base_url('uploads/'.$nota.'/stp_'.$nota.'.png');

        $qrsty = array(
            'border' => 2,
            'padding' => '2',
            'fgcolor' => array(29,32,136),
            'bgcolor' => array(255,255,255), //array(255,255,255)
            'module_width' => 1, // width of a single module in points
            'module_height' => 1 // height of a single module in points
        );
        $dt=$this->angg->cetakPribadi($nota, $nisn);
        $nt=$this->nota->getNota1($nota);
        $tmpl=$nt->nt_tmpl; //template
        // $i=-1;
        $row=0;
        $foto= base_url('uploads/'.$nota.'/'.$dt->ag_nisn.'.jpg');
        $nisn=$dt->ag_nisn;
        $nama=strtoupper($dt->ag_nama);
        $tgll=$dt->ag_tgl=='0000-00-00'?$dt->ag_tgl:date_id(date('Y-m-d', strtotime($dt->ag_tgl)));
        $nis=$dt->ag_induk;
        $prodi=$dt->ag_jurusan;
        $lahir=$dt->ag_tempat.', '.$tgll;
        $ortu='Ortu '.$dt->ag_bapak;
        $alamat1='RT '.$dt->ag_rt.' RW '.$dt->ag_rw.' '.$dt->ag_dusun.' Desa '.$dt->ag_desa;
        $alamat2='Kec '.$dt->ag_kec.', '.$dt->ag_kab;
        $sekolah=$nt->sch_nama;
        $ks=$nt->nt_ks;
        $nip=$nt->nt_nip;
        $tgl=$nt->nt_tgl;
        $nick=$dt->ag_nick;
        // startL        
        $pdf->Image($bg1,$ml+4.5,$row*$boxh+$mt+0.5,$bgw, $bgh); //bg             
        $this->$tmpl($ml,$row,$boxh,$boxw,$bgh,$nisn,$nama,$nis,$prodi,$lahir,$ortu,$alamat1,$alamat2,$sekolah,$ks,$nip,$foto,$ttd,$tgl,$nick,$qrsty,$bg2, $plong);//ktp_id           
        if($ctk==1){
            $pdf->Rect($ml,$row*$boxh+$mt,$boxw,$boxh,'D');//mal
            $pdf->Rect($ml+$boxw,$row*$boxh+$mt,$boxw,$boxh,'D');//Mal
        }else{
            $pdf->Image($plong,$ml+4.5,$row*$boxh+$mt+0.5,$bgw, $bgh,'PNG'); //bg plong
            $pdf->Image($plong,$ml+$boxw+4.5,$row*$boxh+$mt+0.5,$bgw, $bgh,'PNG'); //bgplong
        }
        // endL
        // ==================================================================================
        // startR
        // if($ctk==1){
        //     $pdf->Rect($ml+$boxw,$row*$boxh+$mt,$boxw,$boxh,'D');//Mal
        // }else{
        //     $pdf->Image($plong,$ml+$boxw+4.5,$row*$boxh+$mt+0.5,$bgw, $bgh,'PNG'); //bgplong
        // }
        // endR
        $tipe=$ctk==1?'Cetak_':'';
        $this->response->setContentType('application/pdf');
        $pdf->Output($tipe.$nama.'_'.$sekolah.'.pdf', 'I');
    }

    private function ktp_id($ml,$row,$boxh,$boxw,$bgh,$nisn,$nama,$nis,$prodi,$lahir,$ortu,$alamat1,$alamat2,$sekolah,$ks,$nip,$foto,$ttd,$tgl,$nick,$qrsty,$bg2, $plong){
        $pdf=$this->pdf;
        $ytext=$row*$boxh+18;
        $xdt1=31;
        $xdt2=$xdt1+7;
        //cardL
        $fontaw=14;
        for ($i = 0; $i < 10; $i++) {
            $fontaw -= 0.5;
            $pdf->SetFont('Ubuntu', 'B', $fontaw);
            $lbnama= $pdf->GetStringWidth($nama);
            $lebarnm = $pdf->GetStringWidth($nama);
            if($lebarnm<76){
                break;
            }
        }
        $pdf->SetTextColor(29,32,136);
        $pdf->Text(12,$ytext,($nama));
        $pdf->SetTextColor(0,0,0);
        $pdf->SetFont('UbuntuL', '', 7);
        $pdf->Text(12,$ytext+5.5,'NIS. '.$nis.', '.$prodi);
        $pdf->Text($xdt1,$ytext+9,$lahir);
        $pdf->Text($xdt1,$ytext+12,$ortu);
        $pdf->Text($xdt1,$ytext+15,$alamat1);
        $pdf->Text($xdt1,$ytext+18,$alamat2);
        $pdf->Text($xdt1,$ytext+21.5,'Kepala '.$sekolah);
        $pdf->Text($xdt1, $ytext+31.5,$ks);
        if(!empty($nip)){
            $pdf->Text($xdt1, $ytext+34,'NIP. '.$nip);
        }
        $pdf->Image($foto,$ml+9,$row*$boxh+28,18,24); //foto
        $pdf->Image($ttd,$ml+23,$row*$boxh+40.5,0,12); //ttd
        $pdf->SetFont('UbuntuL', '', 6);
        $pdf->SetXY($ml+9,$row*$boxh+50);
        $pdf->SetFillColor(255, 240, 0);
        $pdf->Rect($ml+11,$row*$boxh+51.5,14,2,'F');
        $pdf->Cell(18,5,$tgl, 0, 0, 'C');
        $pdf->SetFont('Ubuntu', 'I', 6);
        $pdf->Text($ml+8,$ytext+36.5,'Berlaku selama menjadi siswa di '.$sekolah);
        $pdf->write2DBarcode($nisn, 'QRCODE,H', $boxw-20, $row*$boxh+38.5, 15, 15, $qrsty, 'N');
        $pdf->SetXY(76,$row*$boxh+53);
        $pdf->SetFont('Ubuntu', 'B', 8);
        $pdf->Cell(15,5,$nisn, 0, 0, 'C');
        //cardL
        // ======================================
        //cardR
        $pdf->SetTextColor(29,32,136);
        $pdf->StartTransform();
        $pdf->Rotate(-90);
        $pdf->Image($bg2,42.5,$row*$boxh-47.25,$bgh); //bg
        $pdf->SetLineWidth(0.8);
        $pdf->SetDrawColor(29,32,136);
        $pdf->Image($foto,57,$row*$boxh-22.25,26,0, '', '', '', false, 300, '', false, false, 1, false, false, false); //foto
        $pdf->SetDrawColor(0);
        $pdf->SetFont('Ubuntu', 'B', 13);
        $pdf->SetXY(44.5,$row*$boxh+18);
        $pdf->Cell($bgh-4,5,strtoupper($nick), 0, 1, 'C');
        $pdf->SetFont('Ubuntu', 'B', 11);
        $pdf->SetXY(44.5,$row*$boxh+25);
        $pdf->Cell($bgh-4,5,$nisn, 0, 1, 'C');
        $pdf->StopTransform();
        $pdf->SetLineWidth(0.1);
        //cardR
    }

    private function o_smk2($ml,$row,$boxh,$boxw,$bgh,$nisn,$nama,$nis,$prodi,$lahir,$ortu,$alamat1,$alamat2,$sekolah,$ks,$nip,$foto,$ttd,$tgl,$nick,$qrsty,$bg2, $plong){
        $pdf=$this->pdf;
        $ytext=$row*$boxh+18;
        $xdt1=31;
        $xdt2=$xdt1+7;
        //cardL
        $fontaw=14;
        for ($i = 0; $i < 10; $i++) {
            $fontaw -= 0.5;
            $pdf->SetFont('Ubuntu', 'B', $fontaw);
            $lbnama= $pdf->GetStringWidth($nama);
            $lebarnm = $pdf->GetStringWidth($nama);
            if($lebarnm<76){
                break;
            }
        }
        $pdf->SetTextColor(0,0,0);
        $pdf->Text(12,$ytext,($nama));
        $pdf->SetTextColor(0,0,0);
        $pdf->SetFont('UbuntuL', '', 7);
        $pdf->Text(12,$ytext+5.5,'NIS. '.$nis.', '.$prodi);
        $pdf->Text($xdt1,$ytext+9,$lahir);
        $pdf->Text($xdt1,$ytext+12,$ortu);
        $pdf->Text($xdt1,$ytext+15,$alamat1);
        $pdf->Text($xdt1,$ytext+18,$alamat2);
        $pdf->Text($xdt1,$ytext+21.5,'Kepala '.$sekolah);
        $pdf->Text($xdt1, $ytext+31.5,$ks);
        if(!empty($nip)){
            $pdf->Text($xdt1, $ytext+34,'NIP. '.$nip);
        }
        $pdf->Image($foto,$ml+9,$row*$boxh+28,18,24); //foto
        $pdf->Image($ttd,$ml+23,$row*$boxh+40.5,0,12); //ttd
        $pdf->SetFont('UbuntuL', '', 6);
        $pdf->SetXY($ml+9,$row*$boxh+50);
        $pdf->SetFillColor(255, 240, 0);
        $pdf->Rect($ml+11,$row*$boxh+51.5,14,2,'F');
        $pdf->Cell(18,5,$tgl, 0, 0, 'C');
        $pdf->SetFont('Ubuntu', 'I', 6);
        $pdf->Text($ml+8,$ytext+36.5,'Berlaku selama menjadi siswa di '.$sekolah);
        $pdf->write2DBarcode($nisn, 'QRCODE,H', $boxw-20, $row*$boxh+38.5, 15, 15, $qrsty, 'N');
        $pdf->SetXY(76,$row*$boxh+53);
        $pdf->SetFont('Ubuntu', 'B', 8);
        $pdf->Cell(15,5,$nisn, 0, 0, 'C');
        //cardL
        // ======================================
        //cardR
        $pdf->SetTextColor(29,32,136);
        $pdf->Image($bg2,$boxw+$ml+4.5,$row*$boxh+4.5,87, $bgh);
        // $pdf->Image($bg1,$ml+4.5,$row*$boxh+$mt+0.5,$bgw, $bgh); //bg 

        $pdf->StartTransform();
        $pdf->Rotate(-90);
         //bg
        // $pdf->SetLineWidth(0.8);
        // $pdf->SetDrawColor(29,32,136);
        // $pdf->Image($foto,57,$row*$boxh-22.25,26,0, '', '', '', false, 300, '', false, false, 1, false, false, false); //foto
        // $pdf->SetDrawColor(0);
        // $pdf->SetFont('Ubuntu', 'B', 13);
        // $pdf->SetXY(44.5,$row*$boxh+18);
        // $pdf->Cell($bgh-4,5,strtoupper($nick), 0, 1, 'C');
        // $pdf->SetFont('Ubuntu', 'B', 11);
        // $pdf->SetXY(44.5,$row*$boxh+25);
        // $pdf->Cell($bgh-4,5,$nisn, 0, 1, 'C');
        $pdf->StopTransform();
        $pdf->SetLineWidth(0.1);
        //cardR
    }
}

